#!/usr/bin/env bash

interactive=$([ -t 0 ] && echo "-it")

docker run --rm $interactive \
  -v $(pwd):$(pwd) -v /var/run/docker.sock:/var/run/docker.sock \
  -e COMPOSE_PROJECT_NAME=$(basename $(pwd)) -w="$(pwd)" \
  blinkreaction/docker-compose:1.3.0 $*
